pub mod traits;
pub mod aabb;
pub mod ray;
pub mod geometries;
pub mod mesh_structure;
pub mod hittable;
pub mod transformable;
pub mod vertex;
pub mod sub_geometry;
pub mod geometry;
mod triangle;
mod bounded;
